remote_theme: pmarsceill/just-the-docs
aux_links:
  "Edit on GitHub":
    - "https://github.com/petalmd/chapter-rails-blog"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/petalmd/chapter-rails-blog"
gh_edit_branch: "master"
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
search.rel_url: false