remote_theme: pmarsceill/just-the-docs
logo: "https://www.petalmd.com/hubfs/_PetalMD_Sept2018/Logos/PetalMD-logo-coul_RGB.svg"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/petalmd/chapter-rails-blog"
gh_edit_branch: "master"
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
search.rel_url: false
color_scheme: custom
